# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160620_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_post',
            field=models.CharField(default='', max_length=100),
        ),
    ]
