# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_preview_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_post',
            field=models.TextField(default='', max_length=200),
        ),
    ]
