# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160626_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/'),
        ),
    ]
